[[permission]]
identifier = "allow-app-commands"
description = "Allows invoking custom app commands"
commands.allow = [
    "load_settings",
    "save_settings",
    "stream_file",
    "delete_file",
    "show_in_finder",
    "show_notification",
    "aria2_rpc"
]
